WebTruyenHay/Models/Chuong.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyenHay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chuong()
        {
            this.imagechuongs = new HashSet<imagechuong>();
        }
    
        public string IDchuong { get; set; }
        public string TruyenID { get; set; }
        public Nullable<int> SoThuTu { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    
        public virtual Truyen Truyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imagechuong> imagechuongs { get; set; }
    }
}

WebTruyenHay/Models/Truyen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyenHay.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Truyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truyen()
        {
            this.Chuongs = new HashSet<Chuong>();
            this.DanhGias = new HashSet<DanhGia>();
            this.DanhSachDocTruyens = new HashSet<DanhSachDocTruyen>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.TienDoDocs = new HashSet<TienDoDoc>();
            this.TruyenDanhMucs = new HashSet<TruyenDanhMuc>();
        }
        public HttpPostedFileBase UploadImage { get; set; }
        public string IDtruyen { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string TacGia { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TrangThai { get; set; }
        public string imagetruyen { get; set; }
        public string theloai { get; set; }
        public string premium { get; set; }
        public Nullable<int> viewtruyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuong> Chuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachDocTruyen> DanhSachDocTruyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienDoDoc> TienDoDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruyenDanhMuc> TruyenDanhMucs { get; set; }
    }
}

WebTruyenHay/Controllers/truyenController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebTruyenHay.Models;

namespace WebTruyenHay.Controllers
{
    public class truyenController : Controller
    {
        truyenhayEntities7 truyendata = new truyenhayEntities7();
        // GET: truyen
        public async Task<ActionResult> Index(string category)
        {
            await NotifyNewChapters();
            if (category == null)
            {
                var productList = truyendata.Truyens.OrderByDescending(x => x.TieuDe);
                return View(productList);
            }
            else
            {
                var productList = truyendata.Truyens.OrderByDescending(x => x.TieuDe)
                .Where(x => x.theloai == category);
                return View(productList);
            }
        }
        public async Task<ActionResult> Indexuser(string category)
        {
            await NotifyNewChapters();
            if (category == null)
            {
                var productList = truyendata.Truyens.OrderByDescending(x => x.TieuDe);
                return View(productList);
            }
            else
            {
                var productList = truyendata.Truyens.OrderByDescending(x => x.TieuDe)
                .Where(x => x.theloai == category);
                return View(productList);
            }

        }
        // tạo truyện
        public ActionResult Create()
        {
            Truyen truyen1 = new Truyen();
            return View(truyen1);
        }
        [HttpPost]

        public ActionResult Create(Truyen truyen1)
        {
            try
            {
                if (ModelState.IsValid) 
                {
                    if (truyen1.UploadImage != null && truyen1.UploadImage.ContentLength > 0)
                    {
                        string filename = Path.GetFileNameWithoutExtension(truyen1.UploadImage.FileName);
                        string extent = Path.GetExtension(truyen1.UploadImage.FileName);
                        filename = filename + extent;
                        truyen1.imagetruyen = "~/Content/images/" + filename;
                        truyen1.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), filename));
                    }
                   
                    truyen1.IDtruyen = Guid.NewGuid().ToString("N").Substring(0, 8);
                    truyen1.NgayTao = DateTime.Now;
                    truyendata.Truyens.Add(truyen1);
                    truyendata.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message; 
            }
            return View(truyen1);
        }
        // edit truyện
        public ActionResult Edit(String id)
        {
            var product = truyendata.Truyens.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Truyen sach)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var existingProduct = truyendata.Truyens.Find(sach.IDtruyen);
                    if (existingProduct == null)
                    {
                        return HttpNotFound();
                    }

                    // Cập nhật thông tin truyên
                    existingProduct.TieuDe = sach.TieuDe;
                    existingProduct.MoTa = sach.MoTa;
                    existingProduct.theloai = sach.theloai;
                    existingProduct.TrangThai = sach.TrangThai;

                    // Cập nhật hình ảnh nếu có
                    if (sach.UploadImage != null)
                    {
                        string filename = Path.GetFileNameWithoutExtension(sach.UploadImage.FileName);
                        string extent = Path.GetExtension(sach.UploadImage.FileName);
                        filename = filename + extent;
                        existingProduct.imagetruyen = "~/Content/images/" + filename;
                        sach.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), filename));
                    }

                    // Lưu thay đổi vào database
                    truyendata.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(sach);
            }
            catch
            {
                return View();
            }
        }
        //xem chi tiết của người dungf
        public ActionResult Detailsuser(String id)
        {
            var truyen = truyendata.Truyens.Find(id);
            if (truyen == null)
            {
                return HttpNotFound();
            }

            var chapters = truyendata.Chuongs.Where(c => c.TruyenID == id).ToList();

            var viewModel = new TruyenWithChapters
            {
                Truyen = truyen,
                Chapters = chapters
            };

            return View(viewModel);
        }
        public ActionResult Details(String id)
        {
            var truyen = truyendata.Truyens.Find(id);
            if (truyen == null)
            {
                return HttpNotFound();
            }
            var ViewChapters = truyendata.Truyens.Where(c => c.IDtruyen == id).FirstOrDefault();
            var chapters = truyendata.Chuongs.Where(c => c.TruyenID == id).OrderByDescending(c => c.SoThuTu).ToList();
            var danhgia1 = truyendata.DanhGias.Where(s => s.TruyenID == id).ToList();
            ViewChapters.viewtruyen += 1;
            truyendata.SaveChanges(); 

            var viewModel = new TruyenWithChapters
            {
                Truyen = truyen,
                Chapters = chapters,
                DanhGia = danhgia1
            };

            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //add bình luận
        public ActionResult AddComment(string id, TruyenWithChapters model)
        {
            if (ModelState.IsValid)
            {
                var newComment = new DanhGia
                {
                    IDDanhGia = Guid.NewGuid().ToString("N").Substring(0, 8),
                    TruyenID = id,
                    NhanXet = model.NewComment,
                    DiemDanhGia = model.Rating,
                    NgayDanhGia = DateTime.Now
                };

                truyendata.DanhGias.Add(newComment);
                truyendata.SaveChanges();

                return RedirectToAction("Details", new { id = id });
            }

        
            return RedirectToAction("Details", new { id = id });
        }
        // xóa
        public ActionResult Delete(String id)
        {
            var sach = truyendata.Truyens.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            // Xóa sản phẩm
            truyendata.Truyens.Remove(sach);
            truyendata.SaveChanges();

            return RedirectToAction("Index");
        }
        //tìm kiếm
        public ActionResult Search(string searchString)
        {
            var productList = truyendata.Truyens.OrderByDescending(x => x.TieuDe);

            if (!string.IsNullOrEmpty(searchString))
            {
                productList = (IOrderedQueryable<Truyen>)productList.Where(x => x.TieuDe.Contains(searchString));
            }

            return View("Index", productList.ToList());
        }
        public ActionResult Searchuser(string searchString)
        {
            var productList = truyendata.Truyens.OrderByDescending(x => x.TieuDe);

            if (!string.IsNullOrEmpty(searchString))
            {
                productList = (IOrderedQueryable<Truyen>)productList.Where(x => x.TieuDe.Contains(searchString));
            }
            var email = "minhchi521@gmail.com"; // Replace with the actual email or retrieve it dynamically
            var mailService = new MailService();
            Task.Run(() => mailService.SendMailAsync(email, "Test new", "Sản phẩm mượn bị quá hạn"));
            return View("Indexuser", productList.ToList());
        }
        // tìm kiếm nâng cao
        public ActionResult AdvancedSearch(string title, string author, string category)
        {
            var books = truyendata.Truyens.AsQueryable();

            if (!string.IsNullOrEmpty(title))
            {
                books = books.Where(b => b.TieuDe.Contains(title));
            }

            if (!string.IsNullOrEmpty(author))
            {
                books = books.Where(b => b.TacGia.Contains(author));
            }

            if (!string.IsNullOrEmpty(category))
            {
                books = books.Where(b => b.theloai.Contains(category));
            }
            return View("Index", books.ToList());
        }
        public ActionResult AdvancedSearchuser(string title, string author, string category)
        {
            var books = truyendata.Truyens.AsQueryable();

            if (!string.IsNullOrEmpty(title))
            {
                books = books.Where(b => b.TieuDe.Contains(title));
            }

            if (!string.IsNullOrEmpty(author))
            {
                books = books.Where(b => b.TacGia.Contains(author));
            }

            if (!string.IsNullOrEmpty(category))
            {
                books = books.Where(b => b.theloai.Contains(category));
            }
            return View("Indexuser", books.ToList());
        }
        //tạo chương cho truyện
        public ActionResult chuong(String id)
        {
            var sach = truyendata.Truyens.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }

WebTruyenHay/Views/truyen/BuyPremium.cshtml
@{
    ViewBag.Title = "Buy Premium";
}

<h2>Buy Premium Subscription</h2>

<div class="row">
    <div class="col-md-8">
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
        }

        <div class="panel panel-default">
            <div class="panel-heading">Premium Features</div>
            <div class="panel-body">
                <ul>
                    <li>Ad-free reading experience</li>
                    <li>Access to exclusive content</li>
                    <li>Early access to new chapters</li>
                    <li>Offline reading</li>
                </ul>
            </div>
        </div>
        <p>Price: 2000 VND</p>
        @using (Html.BeginForm("ProcessBuyPremium", "truyen", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <button type="submit" class="btn btn-primary">Purchase Premium</button>
        }
    </div>
</div>

WebTruyenHay/Views/truyen/Create.cshtml
@model WebTruyenHay.Models.Truyen

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm(Html.BeginForm("Create", "truyen", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Sach</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.TieuDe, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
        </div>

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.theloai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.theloai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.theloai, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TacGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
        </div>
    </div>
    <div>
        <div colspan="2">
            <input type="file" name="UploadImage" onchange="ChangeImage(this, document.getElementById('previewimg'))" />
            <input type="submit" value="tạo mới" />
        </div>
    </div>
</div>
}

WebTruyenHay/Views/truyen/Details.cshtml
@model WebTruyenHay.Models.TruyenWithChapters
@{
    ViewBag.Title = "Details";
}
<div>
    <h4>Truyen</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Truyen.TieuDe)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Truyen.TieuDe)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Truyen.MoTa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Truyen.MoTa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Truyen.TacGia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Truyen.TacGia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Truyen.imagetruyen)
        </dt>
        <dd>
            <img src="@Url.Content(Model.Truyen.imagetruyen)" alt="@Model.Truyen.TieuDe" style="max-width: 300px; height: auto;" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Truyen.theloai)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Truyen.theloai)
        </dd>
    </dl>
    <div><a href="@Url.Action("doctiep", "truyen")" class="btn btn-danger">Đọc tiếp</a></div>
    <a href="@Url.Action("doccunhat", "truyen")" class="btn btn-danger">Đọc chương cũ</a>
    <a href="@Url.Action("docchuongmoi", "truyen")" class="btn btn-danger">Đọc chương mới</a>
    <button id="likeButton" data-truyen-id="@Model.Truyen.IDtruyen" class="btn btn-secondary">
        <i class="fa fa-heart"></i> Thích
    </button>
</div>
<div>
    <h4>Chapters</h4>
    <hr />
    @if (Model.Chapters != null && Model.Chapters.Any())
    {
        <ul class="list-group">
            @foreach (var chapter in Model.Chapters)
            {
                <li class="list-group-item">
                    @Html.ActionLink(chapter.TieuDe, "ReadTruyen", new { id = chapter.IDchuong })
                </li>
            }
        </ul>
    }
    else
    {
        <p>No chapters available for this story.</p>
    }
    <a href="@Url.Action("Chuong", "Truyen", new { id = Model.Truyen.IDtruyen })" class="btn btn-info">Tạo chương</a>
</div>
<div>
    <h4>Comments and Ratings</h4>
    <hr />
    @using (Html.BeginForm("AddComment", "Truyen", new { id = Model.Truyen.IDtruyen }, FormMethod.Post, new { id = "commentForm" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(model => model.NewComment)
            @Html.TextAreaFor(model => model.NewComment, new { @class = "form-control", rows = "3", id = "commentText" })
            @Html.ValidationMessageFor(model => model.NewComment, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Rating)
            @for (int i = 1; i <= 5; i++)
            {
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.Rating, i, new { @class = "ratingRadio" }) @i
                </label>
            }
            @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
        </div>
        <button type="submit" id="submitButton" class="btn btn-primary" style="display: none;">Submit Comment and Rating</button>
    }
</div>
<div>
    <h4>Existing Comments</h4>
    <hr />
    @if (Model.DanhGia != null && Model.DanhGia.Any())
    {
        <ul class="list-group">
            @foreach (var comment in Model.DanhGia)
            {
                <li class="list-group-item">
                    <strong>@comment.NguoiDung</strong>
                    <p>@comment.NhanXet</p>
                    @if (comment.DiemDanhGia.HasValue)
                    {
                        <small>Rating: @comment.DiemDanhGia / 5</small>
                    }
                    @if (comment.NgayDanhGia.HasValue)
                    {
                        <small class="text-muted">@comment.NgayDanhGia.Value.ToString("dd/MM/yyyy HH:mm")</small>
                    }
                </li>
            }
        </ul>
    }
    else
    {
        <p>No comments available for this story.</p>
    }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Truyen.IDtruyen }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            var $commentText = $('#commentText');
            var $ratingRadios = $('.ratingRadio');
            var $submitButton = $('#submitButton');

            function checkFormValidity() {
                var commentValid = $commentText.val().trim().length > 0;
                var ratingValid = $ratingRadios.is(':checked');

                if (commentValid && ratingValid) {
                    $submitButton.show();
                } else {
                    $submitButton.hide();
                }
            }

            $commentText.on('input', checkFormValidity);
            $ratingRadios.on('change', checkFormValidity);

            checkFormValidity();
        });
    </script>
    <script>
$(document).ready(function() {
    $('#likeButton').click(function() {
        var button = $(this);
        var truyenId = button.data('truyen-id');
        $.ajax({
            url: '@Url.Action("iuthichtruyen", "Truyen")',
            type: 'POST',
            data: { id: truyenId },
            success: function(result) {
                if (result.isLiked) {
                    button.removeClass('btn-secondary').addClass('btn-danger');
                } else {
                    button.removeClass('btn-danger').addClass('btn-secondary');
                }
            },
            error: function() {
                alert('Có lỗi xảy ra. Vui lòng thử lại sau.');
            }
        });
    });
});
    </script>
}

WebTruyenHay/Views/truyen/Index.cshtml
@model IEnumerable<WebTruyenHay.Models.Truyen>

@{
    ViewBag.Title = "Index";
    @Styles.Render("~/Content/nav1.css")
    @Styles.Render("~/Content/themes.css")
}

<body class="@(Session["Theme"] as string ?? "light")-mode">

    <header class="header">
        <div class="container">
            <div class="header-content">
                <div class="logo">
                    <img src="/Content/images/libary.png" alt="BookShoppe' Logo">
                </div>
                <div >
                    <button onclick="toggleTheme()">light</button>
                </div>
                <div class="navsearch">
                    <form class="search-form" action="/Sach/Search" method="get">
                        <input type="text" placeholder="Tìm kiếm sách..." name="searchString">
                        <button type="submit"><i class="fa fa-search"></i> Tìm kiếm</button>
                    </form>
                    <div class="advanced-search-toggle">
                        <a href="#" id="toggleAdvancedSearch">Tìm kiếm nâng cao</a>
                    </div>

                    <div class="advanced-search-form" style="display: none;">
                        <form action="/Sach/AdvancedSearch" method="get">

                            <label for="category">Thể loại:</label>
                            <select name="category" id="category">
                                <option value="">Chọn thể loại</option>
                                <option value="adventure">adventure</option>
                                <option value="Quest">Quest</option>
                                <option value="fantasy">fantasy</option>
                            </select>

                            <label for="year">Năm xuất bản:</label>
                            <select name="year" id="year">
                                <option value="">Chọn năm</option>
                                <option value="2022">2022</option>
                                <option value="2015">2015</option>
                            </select>

                            <label for="author">Tác giả:</label>
                            <input type="text" name="author" id="author" placeholder="Nhập tên tác giả...">
                            <button type="submit"><i class="fa fa-search"></i> Tìm kiếm nâng cao</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </header>
   
    <nav class="nav">
       
        <div class="container">
            <ul>
                <li><a href="/">Trang Chủ</a></li>
                <li>
                    <a href="#">Thể Loại <i class="fa-solid fa-chevron-down fa-xs"></i></a>
                    <div class="dropdown-content">
                        <a href="/Sach/Index?category=fantasy">Fantasy</a>
                        <a href="/Sach/Index?category=Quest">Quest</a>
                        <a href="/Sach/Index?category=adventure">Adventure</a>
                        <a href="/Sach/Index?category=Anime">Anime</a>
                        <a href="/Sach/Index?category=Shoujo">Shoujo</a>
                        <a href="/Sach/Index?category=NgonTinh">Ngôn Tình</a>
                        <a href="/Sach/Index?category=ChuyenSinh">Chuyển Sinh</a>
                        <a href="/Sach/Index?category=Comedy">Comedy</a>
                        <a href="/Sach/Index?category=Comic">Comic</a>
                        <a href="/Sach/Index?category=Demons">Demons</a>
                        <a href="/Sach/Index?category=Detective">Detective</a>
                    </div>
                </li>
                <li><a href="#">Bán Chạy</a></li>
                <li><a href="#">Liên Hệ</a></li>
                <li><a href="@Url.Action("BuyPremium", "truyen")">mua Premium</a></li>
                <div class="right-section">
                <li><a href="@Url.Action("logout","User")">LogOut</a></li>
                <li class="format-hello" style="color:white;">
                    @if (Session["name"] == null)
                    {
                        <span>Hello </span> }
                    else
                    {
                        <span><text>Hello: </text>@Session["name"]</span>}
                    <div class="dropdown-content">
                        <a href="/truyen/profile">Account</a>
                    </div>
                </li>
        </div>
        </ul>
        </div>
    </nav>

    <div class="welcome-banner">
        <div class="container">
            <h1>WELCOME TO BookShoppe'</h1>
            <p>Offering a wide selection of books on thousands of topics at low prices to satisfy any book-lover!</p>
        </div>
    </div>

    <main class="container" style="display:flex;flex-direction:row;">
        <div class="left" style="width:80%">
            <div class="book-grid">
                @foreach (var truyen1 in Model)
                {
                    <div class="book-card" style="width:195px">
                        <img src="@Url.Content(truyen1.imagetruyen)" alt="@truyen1.TieuDe" class="book-image" data-idtruyen="@truyen1.IDtruyen">
                        <div class="book-info">
                            <h3 class="book-title">@truyen1.TieuDe</h3>
                            <div class="book-actions">
                                <a href="@Url.Action("Delete", "truyen", new { id = truyen1.IDtruyen })" class="btn btn-danger">Xóa</a>
                                <a href="@Url.Action("Edit", "truyen", new { id = truyen1.IDtruyen })" class="btn btn-warning">Sửa</a>
                                <a href="@Url.Action("Details", "truyen", new { id = truyen1.IDtruyen})" class="btn btn-info">Chi tiết</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="right" style="width:200px;height:65px;margin-top:10px">
            @Html.Action("top10", "Truyen")
        </div>
    </main>
    <input type="button" value="Create" onclick="redirectToRegister1()" />
</body>

<script>
    const advancedSearchLink = document.getElementById('toggleAdvancedSearch');
    const advancedSearchForm = document.querySelector('.advanced-search-form');

    advancedSearchLink.addEventListener('click', (e) => {
        e.preventDefault();
        if (advancedSearchForm.style.display === 'none' || advancedSearchForm.style.display === '') {
            advancedSearchForm.style.display = 'block';
            advancedSearchLink.textContent = 'Ẩn tìm kiếm nâng cao';
        } else {
            advancedSearchForm.style.display = 'none';
            advancedSearchLink.textContent = 'Tìm kiếm nâng cao';
        }
    });
     function redirectToRegister1() {
        window.location.href = "@Url.Action("Index", "truyen/Create")";
    }

    document.addEventListener('DOMContentLoaded', function () {
        const bookGrid = document.querySelector('.book-grid');

        bookGrid.addEventListener('click', function (event) {
            const clickedElement = event.target;

            if (clickedElement.classList.contains('book-image')) {
                const IDtruyen = clickedElement.getAttribute('data-idtruyen');

                if (IDtruyen) {

                    window.location.href = `/truyen/Details/${IDtruyen}`;
                }
            }
        });
    });
    function toggleTheme() {
        $.ajax({
            url: '/truyen/ToggleTheme',
            type: 'GET',
            success: function (result) {
                if (result.success) {
                    $('body').removeClass('light-mode dark-mode').addClass(result.theme + '-mode');
                    localStorage.setItem('theme', result.theme);
                }
            }
        });
    }

    $(document).ready(function () {
        var savedTheme = localStorage.getItem('theme') || 'light';
        $('body').addClass(savedTheme + '-mode');
    });
</script>